[package]
name = "pnltracker-desktop"
version = "0.1.0"
description = "PnlTracker desktop application"
authors = ["PnlTracker"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.94.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pnltracker_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[features]
desktop-production = ["dep:getrandom", "dep:postgresql_embedded"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
postgresql_embedded = { version = "0.21.0", features = ["blocking", "bundled"], optional = true }
getrandom = { version = "0.3.4", optional = true }
tauri-plugin-shell = "2.3.6"
