# -----------------------------------------------------------
# Dependencies stage
# -----------------------------------------------------------o

FROM node:20.19.0-alpine AS deps

WORKDIR /app

# Install build essentials
RUN apk add --no-cache python3 make g++

# Enable pnpm with specific version
RUN corepack enable \
    && corepack prepare pnpm@10.12.1 --activate

# Copy package files and prisma schema
COPY package.json pnpm-lock.yaml ./
COPY package.json ./

RUN pnpm install

# -----------------------------------------------------------o
# Builder stage
# -----------------------------------------------------------

FROM node:20.19.0-alpine AS builder

# Data directory for database
ENV DATABASE_URL=file:/app/data/docker.db

WORKDIR /app

# Enable pnpm with specific version
RUN corepack enable \
    && corepack prepare pnpm@10.12.1 --activate


# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

COPY . .

#RUN mkdir -p /app/data && chmod 777 /app/data

RUN pnpm nuxt prepare
RUN npx prisma generate
RUN npx prisma migrate deploy
RUN node /app/scripts/seed.mjs
RUN pnpm build

CMD ["tail", "-f", "/dev/null"]

# -----------------------------------------------------------
# Production stage
# -----------------------------------------------------------

FROM node:20.19.0-alpine AS production

# Data directory for database
ENV DATABASE_URL=file:/app/data/docker.db

WORKDIR /app

COPY --from=builder /app/.output ./.output
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/generated/prisma ./generated/prisma
COPY --from=builder /app/data ./data

EXPOSE 3000

# CMD ["tail", "-f", "/dev/null"]
CMD ["node", ".output/server/index.mjs"]

