-- Migration v2: Add instrument types, MAE/MFE, options fields, metadata JSONB
-- Idempotent: uses IF NOT EXISTS for safe re-run

-- Trade: instrumentType
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "instrumentType" TEXT NOT NULL DEFAULT 'any';

-- Trade: MAE / MFE
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "mae" DOUBLE PRECISION;
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "mfe" DOUBLE PRECISION;

-- Trade: Options fields
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "strikePrice" DOUBLE PRECISION;
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "expirationDate" TIMESTAMP(3);
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "optionType" TEXT;
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "premium" DOUBLE PRECISION;

-- Trade: metadata JSONB
ALTER TABLE "SCHEMA_PLACEHOLDER"."Trade" ADD COLUMN IF NOT EXISTS "metadata" JSONB;

-- ImportProfile: instrumentType
ALTER TABLE "SCHEMA_PLACEHOLDER"."ImportProfile" ADD COLUMN IF NOT EXISTS "instrumentType" TEXT NOT NULL DEFAULT 'any';

-- ImportProfile: metadata JSONB
ALTER TABLE "SCHEMA_PLACEHOLDER"."ImportProfile" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
